SELECT * FROM PAYMENTS;

SELECT * FROM employees;

CALL SP_AUTHORIZE_PAYMENTS(16,1);
CALL SP_AUTHORIZE_PAYMENTS(17,2);
CALL SP_AUTHORIZE_PAYMENTS(18,3);
CALL SP_AUTHORIZE_PAYMENTS(19,4);
CALL SP_AUTHORIZE_PAYMENTS(20,1); 

SELECT * FROM authorizes;

SELECT *FROM ORDERS;

CALL SP_GET_TOTAL_PROFIT(@TOTAL);

SELECT @TOTAL;
DELETE FROM authorizes WHERE PAYMENT_ID IN (16,17.18,19,20);

SELECT * FROM VW_CUSTOMER_FLAT_PAYMENT_DETAILS_FOR_ADMIN
WHERE ID=5 AND FLAT_BOOKED=10;

SELECT * FROM INVOICES;

SELECT * FROM financial_transaction;

SELECT * FROM PAYMENTS;

SELECT * FROM address;