DESCRIBE MYDB.BUILDINGS;

INSERT INTO MYDB.BUILDINGS VALUES(1,'LANDMARK SQUARE APT',9,20,'PETERBOROUGH ST.','BOSTON','MA');
INSERT INTO MYDB.BUILDINGS VALUES(2,'YOGI CHHAYA',10,5,'GERMAIN ST','BOSTON','MA');
INSERT INTO MYDB.BUILDINGS VALUES(3,'CUSTOM HOUSE TOWER',12,10,'LINCON ST','BOSTON','MA');
INSERT INTO MYDB.BUILDINGS VALUES(4,'AVALON EXETER',20,1,'EXETER ST','BOSTON','MA');
INSERT INTO MYDB.BUILDINGS VALUES(5,'WEST END APARTMENTS',18,5,'EMERSON ST','BOSTON','MA');
INSERT INTO MYDB.BUILDINGS VALUES(6,'CORDIS MILLIS',7,5,'CANAL ST','WORCESTER','MA');
INSERT INTO MYDB.BUILDINGS VALUES(7,'ALSADA DR',11,10,'WEBSTER ST','WORCESTER','MA');
INSERT INTO MYDB.BUILDINGS VALUES(8,'LINCON APARTMENT',22,5,'BRITTAN SQUARE`','WORCESTER','MA');
INSERT INTO MYDB.BUILDINGS VALUES(9,'ALMONT AVE',15,10,'UNION HILL','CAMBRIDGE','MA');
INSERT INTO MYDB.BUILDINGS VALUES(10,'ROBERTSON TOWER',14,5,'CAMBRIDGE ST','QUINCY','MA');



SELECT * FROM MYDB.BUILDINGS;
