
ALTER TABLE MYDB.FLATS MODIFY COLUMN FLAT_BOOKED_STATUS VARCHAR(10) DEFAULT 'N';
UPDATE MYDB.FLATS SET FLAT_BOOKED_STATUS = 'N' WHERE FLATS.FLAT_BOOKED_STATUS IS NULL;

ALTER TABLE MYDB.ACCOUNTS MODIFY ACCOUNT_NUMBER VARCHAR(45);

ALTER TABLE MYDB.FINANCIAL_TRANSACTION MODIFY INVOICE_ID INT;

ALTER TABLE MYDB.AUTHORIZES DROP PRIMARY KEY, ADD PRIMARY KEY (AUTHORIZATION_ID,PAYMENT_ID);

ALTER TABLE MYDB.INVOICES CHANGE PAYMENTS_PAYMENT_ID PAYMENT_ID INT;

DESCRIBE MYDB.INVOICES;
