DESCRIBE MYDB.EQUIPMENTS;

INSERT INTO MYDB.EQUIPMENTS VALUES(1,'EXCAVATORS',20,'EXA','400');
INSERT INTO MYDB.EQUIPMENTS VALUES(2,'BACKHOE LOADERS',20,'BLACK NIGHT','300');
INSERT INTO MYDB.EQUIPMENTS VALUES(3,'BULLDOZERS',50,'RED BULL','400');
INSERT INTO MYDB.EQUIPMENTS VALUES(4,'MOTOR GRADERS',50,'MOTOR','500');
INSERT INTO MYDB.EQUIPMENTS VALUES(5,'CRAWLER LOADERS',50,'WEB CRAWLER','340');
INSERT INTO MYDB.EQUIPMENTS VALUES(6,'TRENCHERS',30,'TRENCH','600');
INSERT INTO MYDB.EQUIPMENTS VALUES(7,'SCARPERS',40,'SKY SCRAPPER','500');
INSERT INTO MYDB.EQUIPMENTS VALUES(8,'COMMON DUMP TRUCKS',40,'SUMP','900');
COMMIT;



SELECT * FROM MYDB.EQUIPMENTS;