DROP FUNCTION IF EXISTS MYDB.FN_GET_CONSTRUCTION_STATUS;

DELIMITER $$
	CREATE FUNCTION MYDB.FN_GET_CONSTRUCTION_STATUS(V_FLOOR INT, V_TOTAL_FLOORS INT) RETURNS VARCHAR(45)
		DETERMINISTIC
    BEGIN
		DECLARE V_CONS_STATUS VARCHAR(45);
        
        IF V_FLOOR = 0 THEN
			SET V_CONS_STATUS = 'Initiated';
		ELSEIF V_FLOOR < V_TOTAL_FLOORS THEN
			SET V_CONS_STATUS = 'In Progress';
		ELSEIF V_FLOOR = V_TOTAL_FLOORS THEN
			SET V_CONS_STATUS = 'Completed';
		END IF;
	RETURN V_CONS_STATUS;
	END $$
DELIMITER ;