DESCRIBE MYDB.MANUFACTURER;

INSERT INTO MYDB.MANUFACTURER VALUES (1,'RAHUL TITARE');
INSERT INTO MYDB.MANUFACTURER VALUES (2,'KAMLESSH JAIWAL');
INSERT INTO MYDB.MANUFACTURER VALUES (3,'RUCHI GIGRAS');
INSERT INTO MYDB.MANUFACTURER VALUES (4,'PRASAD DABOLHE');
INSERT INTO MYDB.MANUFACTURER VALUES (5,'MEHUL SAGALIYA');
COMMIT;

SELECT * FROM MYDB.MANUFACTURER;
