DESCRIBE MYDB.PAYMENT_STATUS_MASTER;

INSERT INTO MYDB.PAYMENT_STATUS_MASTER VALUES(10, 'CUSTOMER SUBMITTED');
INSERT INTO MYDB.PAYMENT_STATUS_MASTER VALUES(20, 'PAYMENT VERIFIED');
COMMIT;


SELECT * FROM MYDB.PAYMENT_STATUS_MASTER;