USE MYDB;

SELECT * FROM FLATS;

-- PLACE ORDER FOR A FLAT
CALL MYDB.SP_PLACE_ORDERS(6,102); --  CUSTOMER_ID, FLAT_ID

SELECT * FROM MYDB.ORDERS WHERE FLAT_ID=102; -- TO VIEW ORDERS

SELECT * FROM ACCOUNTS WHERE CUSTOMER_ID=6;

-- MAKE PAYMENT
CALL  SP_MAKE_PAYMENT_BY_CUSTOMER(16,'68666885556',250,1); -- ORDER_ID, ACCOUNT NO, AMOUNT TO BE PAID, TYPE OF PAYMENT


SELECT * FROM PAYMENTS;

-- AUTHORIZE PAYMENT BY EMPLOYEE

CALL SP_AUTHORIZE_PAYMENTS(23,2,30); -- PAYMENT_ID, EMPLOYEE_ID

SELECT * FROM INVOICES; 

SELECT * FROM PAYMENTS; -- PAYMENTS STATUS UPDATED

SELECT * FROM FINANCIAL_TRANSACTION;

-- GET BALANCE AMOUNT
SELECT FN_GET_BALANCE_AMOUNT(6,102); -- CUSTOMER_ID, FLAT_ID

-- PLACE ORDER FOR EQUIPMENTS
SELECT * FROM EQUIPMENTS_HAS_MANUFACTURER;

SELECT * FROM EQUIPMENTS;

CALL SP_PLACE_EQUIPMENT_ORDER(2,1,2); -- EMPLOYEE_ID, QTY, EQUIPMENTS_HAS_MANUFACTURER_ID

SELECT * FROM EQUIPMENTS;

-- UPDATING THE CONSTRUCTION STATUS

SELECT * FROM BUILDS;

CALL SP_INSERT_INTO_BUILDS(2,3,0); -- EMP_ID, BLD_ID, FLOOR_COMPLETED

SELECT * FROM BUILDS;

CALL SP_INSERT_INTO_BUILDS(2,3,3); -- EMP_ID, BLD_ID, FLOOR_COMPLETED

SELECT * FROM BUILDS;

CALL SP_GET_TOTAL_PROFIT(@TOTAL); -- GET TOTAL PROFIT;
SELECT @TOTAL;

INSERT INTO MYDB.BUILDINGS VALUES(13,'ROBERT APT',24,5,'CAMBRIDGE ST','QUINCY','MA');

SELECT * FROM VW_CUSTOMER_FLAT_DETAILS;

SELECT * FROM vw_customer_flat_payment_details_for_admin;

SELECT * FROM VW_GET_STATUS_OF_BUILDING;

SELECT * FROM VW_GET_EQUIPMENT_ORDER_DETAILS;	

-- mysqldump --routines -u root -p mydb >F:\Documents\Lectures\Sem1\Database\Assignments\Project\db\sqldump.sql



