DROP PROCEDURE IF EXISTS MYDB.SP_AUTHORIZE_PAYMENTS;

DELIMITER $$
CREATE PROCEDURE MYDB.SP_AUTHORIZE_PAYMENTS ( IN AUTHORIZE_PAYMENT_ID INT, IN AUTHORIZER INT, IN PAYMENT_STATUS INT)
BEGIN
	INSERT INTO MYDB.AUTHORIZES(PAYMENT_ID, EMPLOYEE_ID) VALUES (AUTHORIZE_PAYMENT_ID,AUTHORIZER);
    
     #UPDATE PAYMENT_STATUS IN PAYMENTS TABLE
	UPDATE MYDB.PAYMENTS SET STATUS_ID = PAYMENT_STATUS WHERE PAYMENT_ID = AUTHORIZE_PAYMENT_ID;
END $$
DELIMITER ;

