DROP PROCEDURE IF EXISTS MYDB.SP_CANCEL_ORDER;

DELIMITER $$
	CREATE PROCEDURE MYDB.SP_CANCEL_ORDER (IN NEW_CUSTOMER_ID BIGINT(30), IN FLAT_ID_TOBE_PLACED INT)
		BEGIN
        DECLARE V_ORDER_ID INT;
        DECLARE V_COUNT INT;
         DECLARE RESULT TEXT;
         DECLARE V_PAYMENT_ID INT;
			UPDATE MYDB.ORDERS SET ORDER_STATUS ='Cancelled' WHERE FLAT_ID = FLAT_ID_TOBE_PLACED
            AND CUSTOMER_ID = NEW_CUSTOMER_ID;
            UPDATE MYDB.FLATS SET FLAT_BOOKED_STATUS = 'N' WHERE FLAT_ID = FLAT_ID_TOBE_PLACED;
            
            SELECT ORDER_ID INTO V_ORDER_ID FROM MYDB.ORDERS WHERE FLAT_ID = FLAT_ID_TOBE_PLACED;
            
            SELECT COUNT(ORDER_ID) INTO V_COUNT FROM PAYMENTS WHERE ORDER_ID = V_ORDER_ID;
            
            IF V_ORDER_ID IS NULL THEN
				SET RESULT = 'NO PAYMENT FOUND. PLEASE PAY PENALTY';
			ELSEIF  V_COUNT = 0 THEN
				SET RESULT = 'NO ORDER FOUND';
			ELSE
				UPDATE MYDB.ORDERS SET ORDER_STATUS ='Cancelled' WHERE FLAT_ID = FLAT_ID_TOBE_PLACED
				AND CUSTOMER_ID = NEW_CUSTOMER_ID;
				UPDATE MYDB.FLATS SET FLAT_BOOKED_STATUS = 'N' WHERE FLAT_ID = FLAT_ID_TOBE_PLACED;
                
				INSERT INTO MYDB.DUMMY_PAYMENT (PAYMENT_ID,PAYMENT_DATE,STATUS_ID,ORDER_ID,ACCOUNT_NUMBER,PAYMENT_AMOUNT)
				SELECT PAYMENT_ID, PAYMENT_DATE,STATUS_ID,ORDER_ID,ACCOUNT_NUMBER,PAYMENT_AMOUNT 
				FROM PAYMENTS WHERE ORDER_ID = V_ORDER_ID LIMIT 1;
                
                DELETE FROM MYDB.FINANCIAL_TRANSACTION WHERE PAYMENT_ID IN 
                (SELECT PAYMENT_ID FROM PAYMENTS WHERE ORDER_ID = V_ORDER_ID);
                
                DELETE FROM MYDB.AUTHORIZES WHERE PAYMENT_ID IN 
                (SELECT PAYMENT_ID FROM PAYMENTS WHERE ORDER_ID = V_ORDER_ID);
                
                DELETE FROM MYDB.INVOICES WHERE PAYMENT_ID IN 
                 (SELECT PAYMENT_ID FROM PAYMENTS WHERE ORDER_ID = V_ORDER_ID);
                
                DELETE FROM MYDB.PAYMENTS WHERE ORDER_ID = V_ORDER_ID;
                
                IF V_COUNT = 1 THEN
					SET RESULT = 'ORDER CANCELLED BUT MONEY WILL NOT BE RETURNED';
				ELSE                
					SET RESULT = 'ORDER CANCELLED SUCCESSFULLY';
				END IF;
                
            END IF;    
            SELECT RESULT AS MSG;
        END $$
DELIMITER ;