DROP PROCEDURE IF EXISTS MYDB.SP_INSERT_INTO_BUILDS;

DELIMITER $$
CREATE PROCEDURE MYDB.SP_INSERT_INTO_BUILDS(IN EMPL_ID INT, IN BLD_ID INT, IN V_FLOOR_COMPLETED INT)
BEGIN
	DECLARE V_TOTAL_FLOORS INT;
    DECLARE V_COUNT INT;
    
    SELECT NO_OF_FLOORS INTO V_TOTAL_FLOORS FROM MYDB.BUILDINGS  WHERE BUILDING_ID = BLD_ID;    
    SELECT COUNT(*) INTO V_COUNT FROM MYDB.BUILDS WHERE BUILDING_ID = BLD_ID;
    
    IF V_COUNT = 0 THEN
		INSERT INTO MYDB.BUILDS (EMPLOYEE_ID, BUILDING_ID, CONSTRUCTION_STATUS, FLOORS_COMPLETED) 
		VALUES (EMPL_ID, BLD_ID, FN_GET_CONSTRUCTION_STATUS(V_FLOOR_COMPLETED,V_TOTAL_FLOORS), V_FLOOR_COMPLETED);
	ELSE 
		UPDATE MYDB.BUILDS SET CONSTRUCTION_STATUS = FN_GET_CONSTRUCTION_STATUS(V_FLOOR_COMPLETED,V_TOTAL_FLOORS),
        FLOORS_COMPLETED = V_FLOOR_COMPLETED,BUILDS.EMPLOYEE_ID = EMPL_ID  WHERE BUILDS.BUILDING_ID = BLD_ID;
    END IF;
END $$
DELIMITER ;



