DROP PROCEDURE IF EXISTS MYDB.SP_PLACE_ORDERS;

DELIMITER $$
	CREATE PROCEDURE MYDB.SP_PLACE_ORDERS (IN NEW_CUSTOMER_ID BIGINT(30), IN FLAT_ID_TOBE_PLACED INT)
	BEGIN
		DECLARE FLAT_STATUS VARCHAR(10);
        SELECT FLAT_BOOKED_STATUS INTO FLAT_STATUS FROM MYDB.FLATS WHERE FLAT_ID = FLAT_ID_TOBE_PLACED;        
        IF (FLAT_STATUS ='N') THEN
			INSERT INTO MYDB.ORDERS (CUSTOMER_ID,FLAT_ID,ORDER_STATUS) 
            VALUES (NEW_CUSTOMER_ID,FLAT_ID_TOBE_PLACED,'Booked');
            SELECT 'FLAT BOOKED' AS MSG;
		ELSE
			SELECT 'FLAT ALREADY BOOKED' AS MSG;
        END IF ;
    END $$
DELIMITER ;