DROP TRIGGER IF EXISTS MYDB.TR_AFTER_AUTHORISE_INSERT;

DELIMITER $$
CREATE TRIGGER MYDB.TR_AFTER_AUTHORISE_INSERT
	AFTER INSERT ON MYDB.AUTHORIZES
		FOR EACH ROW
        BEGIN
        DECLARE V_ORDER_ID INT;
        DECLARE V_CUSTOMER_ID BIGINT(30);
        DECLARE V_FLAT_ID INT;
        DECLARE V_BALANCE_AMOUNT DOUBLE;
        DECLARE V_BUILDING_ID INT;
        DECLARE V_FLAT_NO INT;
        DECLARE V_STATUS VARCHAR(45);
       
			#INSERT VALUE IN INVOICES TABLE AFTER AUTHORIZATION
			INSERT INTO MYDB.INVOICES (PAYMENT_ID) VALUES (NEW.PAYMENT_ID);
            
            #UPDATE INVOICE_ID IN FINANCIAL_TRANSACTION FOR THE PAYMENT AUTHORISED
            UPDATE MYDB.FINANCIAL_TRANSACTION SET INVOICE_ID = LAST_INSERT_ID() WHERE PAYMENT_ID = NEW.PAYMENT_ID;
            
           
            
            SELECT ORDER_ID INTO V_ORDER_ID FROM MYDB.PAYMENTS WHERE PAYMENTS.PAYMENT_ID = NEW.PAYMENT_ID;
            
            SELECT ORDERS.CUSTOMER_ID, ORDERS.FLAT_ID INTO V_CUSTOMER_ID, V_FLAT_ID FROM MYDB.ORDERS
            WHERE ORDERS.ORDER_ID = V_ORDER_ID;
            
            SELECT FLATS.BUILDING_ID,FLATS.FLAT_NO 
            INTO V_BUILDING_ID,V_FLAT_NO FROM MYDB.FLATS WHERE FLATS.FLAT_ID = V_FLAT_ID;
            
            SELECT MYDB.FN_GET_BALANCE_AMOUNT(V_CUSTOMER_ID,V_FLAT_ID) INTO V_BALANCE_AMOUNT;
            
            SELECT STATUS INTO V_STATUS FROM MYDB.VW_GET_STATUS_OF_BUILDING WHERE BUILDING_ID=V_BUILDING_ID;
            
            IF (V_BALANCE_AMOUNT = 0 AND V_STATUS = 'Completed') THEN
				INSERT INTO MYDB.ADDRESS (FLAT_NO,BUILDING_ID, CUSTOMER_ID) VALUES (V_FLAT_NO, V_BUILDING_ID, V_CUSTOMER_ID);

			ELSEIF(V_BALANCE_AMOUNT = 0 AND (V_STATUS ='Initiated' OR V_STATUS = 'Completed')) THEN				
                 UPDATE MYDB.PAYMENTS SET STATUS_ID = 10 WHERE PAYMENT_ID = NEW.PAYMENT_ID;
                 UPDATE MYDB.FINANCIAL_TRANSACTION SET INVOICE_ID = NULL WHERE PAYMENT_ID = NEW.PAYMENT_ID;
			END IF;
        END $$
DELIMITER ;