## TO VIEW CUSTOMER BOOKED FLAT DETAILS

CREATE VIEW MYDB.VW_CUSTOMER_FLAT_DETAILS AS
SELECT  CUSTOMER.ID, CUSTOMER.FIRST_NAME, CUSTOMER.LAST_NAME, FLATS.FLAT_NO, 
BUILDINGS.BUILDING_ID, BUILDINGS.BUILDING_NAME, BUILDINGS.STREET, BUILDINGS.CITY, BUILDINGS.STATE
,ORDERS.FLAT_ID
FROM MYDB.CUSTOMER
INNER JOIN MYDB.ORDERS
ON CUSTOMER.ID = ORDERS.CUSTOMER_ID
INNER JOIN MYDB.FLATS
ON ORDERS.FLAT_ID = FLATS.FLAT_ID
INNER JOIN MYDB.BUILDINGS
ON FLATS.BUILDING_ID = BUILDINGS.BUILDING_ID
WITH CHECK OPTION;

#DROP VIEW MYDB.VW_CUSTOMER_FLAT_DETAILS;