## TO VIEW CUSTOMER PAYMENT DETAILS

CREATE VIEW MYDB.VW_CUSTOMER_FLAT_PAYMENT_DETAILS_FOR_ADMIN AS
SELECT CUSTOMER.ID, CUSTOMER.FIRST_NAME, CUSTOMER.LAST_NAME,ORDERS.ORDER_ID, 
PAYMENTS.PAYMENT_DATE, PAYMENTS.ACCOUNT_NUMBER, PAYMENTS.PAYMENT_AMOUNT, FLATS.FLAT_ID AS 'FLAT_BOOKED',
PAYMENT_STATUS_MASTER.STATUS_NAME AS 'PAYMENT STATUS'
FROM MYDB.CUSTOMER
INNER JOIN MYDB.ORDERS
ON CUSTOMER.ID = ORDERS.CUSTOMER_ID
INNER JOIN MYDB.PAYMENTS
ON ORDERS.ORDER_ID = PAYMENTS.ORDER_ID
INNER JOIN MYDB.FLATS
ON ORDERS.FLAT_ID = FLATS.FLAT_ID
INNER JOIN MYDB.PAYMENT_STATUS_MASTER
ON PAYMENT_STATUS_MASTER.STATUS_ID = PAYMENTS.STATUS_ID
WITH CHECK OPTION;

# DROP VIEW VW_CUSTOMER_FLAT_PAYMENT_DETAILS_FOR_ADMIN

