CREATE VIEW MYDB.VW_GET_STATUS_OF_BUILDING AS
SELECT BUILDINGS.BUILDING_ID, BUILDINGS.BUILDING_NAME,
BUILDS.CONSTRUCTION_STATUS AS 'STATUS', BUILDS.FLOORS_COMPLETED, BUILDINGS.NO_OF_FLOORS,
(BUILDINGS.NO_OF_FLOORS - BUILDS.FLOORS_COMPLETED) AS 'LEFT TO BUILD'
FROM BUILDS, BUILDINGS
WHERE BUILDINGS.BUILDING_ID = BUILDS.BUILDING_ID
WITH CHECK OPTION;


#DROP VIEW MYDB.VW_GET_STATUS_OF_BUILDING;
